import type { MediaFile } from './definitions';

export const mockFiles: MediaFile[] = [
  {
    id: '1',
    name: 'Vacation Photo.jpg',
    type: 'image',
    size: '4.5 MB',
    dateAdded: '2023-10-26T10:00:00Z',
    tags: ['vacation', 'beach', 'sunset'],
    url: '#',
  },
  {
    id: '2',
    name: 'Project Proposal.pdf',
    type: 'document',
    size: '1.2 MB',
    dateAdded: '2023-10-25T15:30:00Z',
    tags: ['work', 'project', 'q4'],
    url: '#',
  },
  {
    id: '3',
    name: 'Product Demo.mp4',
    type: 'video',
    size: '54.1 MB',
    dateAdded: '2023-10-24T09:00:00Z',
    tags: ['work', 'demo', 'presentation'],
    url: '#',
  },
  {
    id: '4',
    name: 'Mountain Trip.jpg',
    type: 'image',
    size: '6.1 MB',
    dateAdded: '2023-10-22T18:45:00Z',
    tags: ['travel', 'mountains', 'hiking'],
    url: '#',
  },
  {
    id: '5',
    name: 'Podcast Episode 3.mp3',
    type: 'audio',
    size: '25.8 MB',
    dateAdded: '2023-10-21T11:20:00Z',
    tags: ['podcast', 'interview', 'tech'],
    url: '#',
  },
  {
    id: '6',
    name: 'quarterly-report.docx',
    type: 'document',
    size: '850 KB',
    dateAdded: '2023-10-20T14:00:00Z',
    tags: ['finance', 'report', 'work'],
    url: '#',
  },
    {
    id: '7',
    name: 'City Nightscape.jpg',
    type: 'image',
    size: '8.2 MB',
    dateAdded: '2023-10-19T22:10:00Z',
    tags: ['city', 'night', 'urban'],
    url: '#',
  },
  {
    id: '8',
    name: 'Architectural Sketch.png',
    type: 'image',
    size: '2.3 MB',
    dateAdded: '2023-10-18T13:00:00Z',
    tags: ['design', 'architecture', 'drawing'],
    url: '#',
  },
];
